// src/config/emergency/protocols.ts
// ============================================================
// v3 — adds whileWaiting + doNot to every protocol
// ============================================================

import type { EmergencyProtocol } from './types';

export const EMERGENCY_PROTOCOLS: EmergencyProtocol[] = [
  {
    type: 'medical',
    label: 'Medical Emergency',
    icon: '🚑',
    call911: true,
    immediateActions: [
      'Do NOT move the injured person unless they are in immediate danger',
      'Apply direct pressure to any bleeding with a clean cloth',
      'If person is unresponsive and not breathing, begin CPR if trained',
      'Send someone to the gate to guide the ambulance in',
    ],
    contactPriority: ['911', 'siteSuper', 'safetyOfficer'],
    equipmentNeeded: ['AED', 'first-aid-kit'],
    musterRequired: false,
    criticalNotes: [
      'Do NOT remove an impaled object — stabilize it in place',
      'For suspected spinal injury, do NOT move the person — wait for EMS',
      'Note the time of injury and any substances involved for EMS',
    ],
    whileWaiting: [
      'Stay with the injured person — do not leave them alone',
      'Keep them warm (cover with a jacket or blanket)',
      'If conscious, keep them calm and talking',
      'Monitor their breathing — be ready to start CPR if it stops',
      'Note the time of injury to relay to EMS when they arrive',
      'Send someone to the site entrance to flag down the ambulance',
    ],
    doNot: [
      'Do NOT give food or water (surgery risk)',
      'Do NOT remove a hard hat or helmet unless trained',
      'Do NOT move someone with a possible spinal injury',
      'Do NOT remove an impaled object',
      'Do NOT apply a tourniquet unless trained and bleeding is life-threatening',
    ],
  },
  {
    type: 'fire',
    label: 'Fire',
    icon: '🔥',
    call911: true,
    immediateActions: [
      'Activate the nearest fire alarm pull station',
      'Evacuate via the nearest exit — DO NOT use elevators',
      'Close doors behind you as you exit',
      'Report to the muster point for headcount',
    ],
    contactPriority: ['911', 'siteSuper', 'safetyOfficer'],
    equipmentNeeded: ['fire-extinguisher-abc'],
    musterRequired: true,
    criticalNotes: [
      'Only attempt to fight a fire if it is small, you have a clear exit, and you are trained',
      'If smoke is heavy, stay low — crawl if necessary',
      'Do NOT re-enter the building for any reason',
    ],
    whileWaiting: [
      'Report to muster point and stay there until headcount is complete',
      'Tell the Accountability Officer if you know someone is still inside',
      'Watch for smoke or fire spread — move further away if needed',
      'Direct the fire department to the nearest hydrant and fire access road',
      'Keep site entrance clear for emergency vehicles',
    ],
    doNot: [
      'Do NOT re-enter the building for any reason — including personal belongings',
      'Do NOT use elevators',
      'Do NOT open doors that are hot to the touch',
      'Do NOT fight a large fire — evacuate immediately',
      'Do NOT block fire lanes or hydrants with vehicles or equipment',
    ],
  },
  {
    type: 'equipment-fire',
    label: 'Equipment / Electrical Fire',
    icon: '🔌🔥',
    call911: true,
    immediateActions: [
      'Alert all workers in the immediate area — clear a minimum 50-foot perimeter',
      'De-energize the equipment at the disconnect or breaker if it can be done safely from a distance',
      'For hydraulic/fuel fires: do NOT attempt to extinguish — evacuate and call 911 (pressurized fluid can spray)',
      'For small electrical fires only: use a CO₂ or dry chemical (Class BC/ABC) extinguisher — NEVER water on energized equipment',
      'Shut down adjacent equipment to prevent fire spread to other machines',
    ],
    contactPriority: ['911', 'siteSuper', 'safetyOfficer'],
    equipmentNeeded: ['fire-extinguisher-co2', 'fire-extinguisher-abc'],
    musterRequired: true,
    criticalNotes: [
      'OSHA 29 CFR 1926.150: Only personnel trained in portable fire extinguisher use may attempt to fight any fire',
      'Hydraulic fluid fires burn at 500°F+ and can reignite — do not assume the fire is out',
      'Burning electrical insulation and plastics release hydrogen cyanide and other toxic fumes — stay upwind',
      'If the fire involves a generator, welder, or compressor with a fuel tank, treat as a fuel fire — evacuate 100 feet minimum',
      'Hot work (welding/cutting) fires per OSHA 1926.352: ensure fire watch remains 30 minutes after work stops',
    ],
    whileWaiting: [
      'Confirm the equipment is de-energized (lockout/tagout if trained and safe to do so)',
      'Keep all personnel upwind — burning plastics, hydraulic fluid, and insulation produce toxic smoke',
      'Monitor for fire spread to adjacent equipment, fuel containers, or structures',
      'Have someone meet the fire department at the gate with info on what equipment is burning and what fuels/fluids it contains',
      'Account for all workers who were operating or near the equipment',
      'If diesel or hydraulic tanks are involved, warn fire department of rupture/BLEVE risk',
    ],
    doNot: [
      'Do NOT use water on an energized electrical fire (electrocution risk per OSHA 1910.157)',
      'Do NOT approach a hydraulic fire — pressurized fluid can spray burning oil 20+ feet',
      'Do NOT attempt to move burning equipment with another machine',
      'Do NOT fight any fire larger than a small wastebasket — evacuate immediately (OSHA 1910.157(g))',
      'Do NOT re-enter the area until the fire department declares it safe — equipment can reignite',
      'Do NOT disconnect fuel lines on burning equipment — risk of fuel spray and flash fire',
    ],
  },
  {
    type: 'chemical',
    label: 'Chemical / HazMat Spill',
    icon: '☢️',
    call911: true,
    immediateActions: [
      'Move UPWIND and away from the spill — do NOT walk through it',
      'If chemical contact: flush affected area with water for 15+ minutes',
      'Evacuate the immediate area and warn others nearby',
      'Identify the chemical if you can do so safely (SDS / label)',
    ],
    contactPriority: ['911', 'safetyOfficer', 'siteSuper'],
    equipmentNeeded: ['eyewash-station', 'emergency-shower', 'spill-kit'],
    musterRequired: true,
    criticalNotes: [
      'Have the Safety Data Sheet (SDS) ready for EMS — know where they are stored',
      'Do NOT attempt to clean up the spill unless trained and equipped',
      'Remove contaminated clothing carefully — avoid spreading the substance',
    ],
    whileWaiting: [
      'Continue flushing eyes/skin if contact occurred — do NOT stop early',
      'Keep the Safety Data Sheet (SDS) accessible for HazMat team',
      'Warn others to stay upwind and keep a wide perimeter',
      'Monitor anyone exposed for symptoms: dizziness, nausea, difficulty breathing',
      'If someone exposed becomes unconscious, start CPR only if safe to do so (check for chemical on face/mouth)',
    ],
    doNot: [
      'Do NOT walk through or touch the spilled material',
      'Do NOT attempt cleanup without proper PPE and training',
      'Do NOT use your phone within 50ft of a flammable spill',
      'Do NOT induce vomiting if a chemical was swallowed — call Poison Control',
      'Do NOT rub eyes if exposed — flush with water only',
    ],
  },
  {
    type: 'structural',
    label: 'Structural Collapse / Cave-in',
    icon: '🏗️',
    call911: true,
    immediateActions: [
      'Move away from the collapse area immediately',
      'Do NOT attempt rescue unless trained — secondary collapse is likely',
      'Account for all workers who were in or near the area',
      'Mark the area as dangerous and prevent others from entering',
    ],
    contactPriority: ['911', 'siteSuper', 'safetyOfficer'],
    equipmentNeeded: ['first-aid-kit'],
    musterRequired: true,
    criticalNotes: [
      'If someone is trapped, note their last known location for rescue teams',
      'Do NOT use heavy equipment near the collapse — vibration can worsen it',
      'Keep all non-essential personnel well away from the area',
    ],
    whileWaiting: [
      'If someone is trapped and conscious, keep talking to them — reassure them help is coming',
      'Note the last known location of every missing worker',
      'Mark the collapse perimeter so rescue teams know the affected area',
      'Have someone meet rescue teams at the gate with site layout info',
      'Keep the area quiet — rescue teams may need to listen for trapped workers',
    ],
    doNot: [
      'Do NOT enter a collapse zone — secondary collapse kills rescuers',
      'Do NOT use heavy equipment near the collapse',
      'Do NOT assume the structure is stable — aftershocks of collapse are common',
      'Do NOT remove debris from on top of someone unless trained',
      'Do NOT turn off utilities unless you are certain it is safe to do so',
    ],
  },
  {
    type: 'weather',
    label: 'Severe Weather',
    icon: '⛈️',
    call911: false,
    immediateActions: [
      'Move to the designated weather shelter or interior room immediately',
      'Stay away from windows, metal structures, and heavy equipment',
      'If lightning: stop all crane, steel, and outdoor elevated work immediately',
      'Monitor weather radio or alerts for all-clear',
    ],
    contactPriority: ['siteSuper', 'safetyOfficer'],
    equipmentNeeded: [],
    musterRequired: false,
    criticalNotes: [
      'Tornado: get to lowest floor, interior room, away from windows',
      'Lightning 30/30 rule: if thunder within 30 seconds of flash, take shelter; wait 30 min after last thunder',
      'Extreme heat: watch for heat stroke (confusion, no sweating, hot skin) — call 911',
    ],
    whileWaiting: [
      'Stay in shelter until the all-clear is given by the Site Super or Safety Officer',
      'Account for all workers in your zone — report missing to Accountability Officer',
      'Keep your phone charged and available for updates',
      'If sheltering for tornado: get under a sturdy desk or table, protect your head',
      'Monitor NOAA Weather Radio or phone alerts for updates',
    ],
    doNot: [
      'Do NOT go outside to "check" the weather — wait for official all-clear',
      'Do NOT shelter under trees, near metal fences, or in open vehicles during lightning',
      'Do NOT resume crane, steel, or elevated work until 30 minutes after the last thunder',
      'Do NOT ignore heat illness symptoms in yourself or coworkers — they can escalate quickly',
    ],
  },
  {
    type: 'utility',
    label: 'Utility Emergency',
    icon: '⚡',
    call911: false,
    immediateActions: [
      'Gas leak: evacuate immediately, do NOT operate any switches or electronics',
      'Electrical: do NOT touch the victim or source — call 911 if someone is injured',
      'Water main break: shut off water if safe, move equipment away',
      'Report to the appropriate utility provider',
    ],
    contactPriority: ['utility', 'siteSuper', 'safetyOfficer'],
    equipmentNeeded: [],
    musterRequired: false,
    criticalNotes: [
      'Gas leak: move at least 300 feet away before using a phone or radio',
      'Downed power line: stay 35+ feet away and keep others back',
      'If someone is in contact with electrical source: do NOT touch them — call 911',
    ],
    whileWaiting: [
      'Keep everyone away from the affected area until the utility company arrives',
      'Gas leak: keep the area ventilated if indoors (open doors/windows from outside)',
      'Electrical: mark the area around downed lines or exposed wiring',
      'Note any damage to underground utilities from excavation',
      'If utility company gives an ETA, relay to Site Super',
    ],
    doNot: [
      'Do NOT use phones, radios, or any electronics near a gas leak (spark risk)',
      'Do NOT drive over a downed power line',
      'Do NOT touch someone in contact with an electrical source',
      'Do NOT try to repair utility lines yourself',
      'Do NOT assume a line is dead — treat all lines as live',
    ],
  },
  {
    type: 'threat',
    label: 'Active Threat / Security',
    icon: '🚨',
    call911: true,
    immediateActions: [
      'RUN: if you can safely exit, do so immediately',
      'HIDE: if you cannot exit, find a room, lock or barricade the door, silence your phone',
      'FIGHT: as an absolute last resort only',
      'Call 911 when safe — whisper if you must',
    ],
    contactPriority: ['911', 'siteSuper', 'safetyOfficer'],
    equipmentNeeded: [],
    musterRequired: false,
    criticalNotes: [
      'Do NOT pull the fire alarm — it causes people to gather in the open',
      'When police arrive: show empty hands, follow all commands, do not point or yell',
      'Do NOT post on social media during an active incident',
    ],
    whileWaiting: [
      'If hiding: remain silent, stay away from doors and windows',
      'Keep your phone on silent — vibrate can be heard',
      'If you can safely text 911 updates, do so (number of people with you, your location)',
      'Do NOT open the door for anyone unless you are certain it is law enforcement',
      'Once police secure the area, follow their instructions exactly',
    ],
    doNot: [
      'Do NOT pull the fire alarm',
      'Do NOT run toward the threat to investigate',
      'Do NOT carry anything in your hands when approaching police',
      'Do NOT post on social media during the incident (reveals positions)',
      'Do NOT leave your hiding place until police give the all-clear',
    ],
  },
];
