/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

declare let self: ServiceWorkerGlobalScope;

// Extended NotificationOptions for iOS Safari compatibility
// TypeScript's built-in type is missing some Web Notification API properties
interface ExtendedNotificationOptions extends NotificationOptions {
  vibrate?: number[];
  renotify?: boolean;
  actions?: Array<{
    action: string;
    title: string;
    icon?: string;
  }>;
}

// Precache static assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();
clientsClaim();

// Skip waiting to activate new service worker immediately
self.skipWaiting();

// ============================================
// Push Notification Handler (iOS Safari Compatible)
// ============================================
self.addEventListener('push', (event: PushEvent) => {
  console.log('[SW] Push received:', event);

  if (!event.data) {
    console.warn('[SW] Push event has no data');
    return;
  }

  try {
    const payload = event.data.json();
    const { title, body, url, data } = payload;

    // Determine if this is a high-priority notification
    const isHighPriority = data?.severity === 'critical' || data?.severity === 'high';

    // iOS-OPTIMIZED notification options for lock screen delivery
    const notificationOptions: ExtendedNotificationOptions = {
      body: body || '',
      icon: '/icon-192.png',
      badge: '/badge-96.png',
      tag: data?.category || 'default',
      
      // Keep high-priority notifications visible until user interacts
      requireInteraction: isHighPriority,
      
      // CRITICAL FOR iOS: Must be false for sound to play
      silent: false,
      
      // Vibration pattern for mobile devices (iOS supports in PWA mode)
      vibrate: isHighPriority ? [200, 100, 200, 100, 200] : [200, 100, 200],
      
      // Allow re-notification for same tag (updates)
      renotify: true,
      
      // iOS action buttons (shown on lock screen)
      actions: [
        {
          action: 'open',
          title: 'Open',
        },
        {
          action: 'dismiss',
          title: 'Dismiss',
        },
      ],
      
      // Data payload for click handling
      data: {
        url: url || '/dashboard',
        notificationId: data?.notificationId,
        category: data?.category,
        severity: data?.severity,
        timestamp: Date.now(),
      },
    };

    event.waitUntil(
      self.registration.showNotification(title || 'ATTS Portal', notificationOptions)
    );
    
    console.log('[SW] Notification shown:', title, 'Severity:', data?.severity);
  } catch (error) {
    console.error('[SW] Failed to parse push payload:', error);
    
    // Fallback: show raw text if JSON parse fails
    const text = event.data?.text() || 'New notification';
    event.waitUntil(
      self.registration.showNotification('ATTS Portal', { 
        body: text,
        icon: '/icon-192.png',
        silent: false,
      })
    );
  }
});

// ============================================
// Notification Click Handler (iOS Compatible)
// ============================================
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  console.log('[SW] Notification clicked:', event.notification.tag, 'Action:', event.action);

  event.notification.close();

  // Handle "dismiss" action explicitly - don't open app
  if (event.action === 'dismiss') {
    console.log('[SW] Notification dismissed by user');
    return;
  }

  // Handle "open" action or default click (no action specified)
  const urlToOpen = event.notification.data?.url || '/dashboard';

  event.waitUntil(
    self.clients.matchAll({ 
      type: 'window', 
      includeUncontrolled: true 
    }).then((clientList) => {
      // Check if app is already open in a window
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          // Navigate existing window to the URL and focus it
          console.log('[SW] Focusing existing window');
          client.postMessage({ type: 'NAVIGATE', url: urlToOpen });
          return client.focus();
        }
      }

      // Open new window if not found
      if (self.clients.openWindow) {
        console.log('[SW] Opening new window:', urlToOpen);
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});

// ============================================
// Notification Close Handler (for analytics)
// ============================================
self.addEventListener('notificationclose', (event: NotificationEvent) => {
  console.log('[SW] Notification closed without interaction:', event.notification.tag);
  // Could send analytics here if needed
});

// ============================================
// Message Handler (for app communication)
// ============================================
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

